@startuml
|Пользователь|
start
:Ввод логина и пароля;
|#AntiqueWhite|Система "Backet"|
:Проверка данных;
if (Данные верны?) then (да)
  :Генерация токена доступа;
  :Установка сессии пользователя;
  :Отправка подтверждения;
else (нет)
  :Отправка сообщения об ошибке;
  stop
endif
:Загрузка данных пользователя;
|Пользователь|
if (Данные загружены?) then (да)
  :Авторизация успешна;
else (нет)
  :Показ сообщения об ошибке;
  stop
endif
:Выбор "Далее";
stop
@enduml