@startuml
|Пользователь|
start
:Авторизация;
if (Авторизация успешна?) then (да)
  :Выбор "Добавить данные";
  :Открытие формы ввода данных;
  :Ввод результатов игры;
  :Подтверждение данных;
  :Сохранение данных;
else (нет)
  :Показать сообщение об ошибке;
  stop
endif
:Выбор "Далее";
stop
@enduml