@startuml
scale 350 width

[*] --> LoggedOut : Приложение запущено

state LoggedOut {
  [*] --> EnterCredentials : Пользователь не аутентифицирован
  EnterCredentials --> ValidateCredentials : Ввод учетных данных
}

state EnterCredentials {
  [*] --> Enter : Начало ввода данных
  Enter --> Validate : Проверка данных
}

state ValidateCredentials {
  [*] --> GrantAccess : Данные верны
  GrantAccess --> [*] : Успешная аутентификация
  Validate --> [*] : Данные не верны
}

state LoggedIn {
  [*] --> LoggedOut : Выход из учетной записи
}
@enduml